In [2]:
import tensorflow as tf

In [3]:
import keras.preprocessing as k_pre

Using TensorFlow backend.


In [4]:
import numpy as np
import random
from sklearn.model_selection import train_test_split as t_split
from PIL import Image
import pandas as pd
import timeit

In [5]:
data_dir=r'C:/Users/Victor/Desktop/Project-Safe-Waters-v1-master/IBM Machine Learning/10K_Model_Test/10k/'
lab_path=r'C:/Users/Victor/Desktop/Project-Safe-Waters-v1-master/IBM Machine Learning/10K_Model_Test/'

In [6]:
labels=pd.read_csv(lab_path+'labels.csv')
labels.head()

Labels
0  1.487000
1  3.471497
2  1.057709
3  3.586395
4  4.017059

In [7]:
lab_data=labels.iloc[:,].values
type(lab_data)

numpy.ndarray

In [8]:
lab_data[0]

array([1.487])

In [9]:
no_of_images=10000
img_h=150
img_w=150
img=np.zeros((no_of_images,img_h,img_w,3))
def load_img(no_of_images,img_h,img_w):
    
    img_size=(img_h,img_w)
    for i in range(no_of_images):
        img_got=Image.open(data_dir+'Grab'+str(i)+'.jpg')
        img_gotr=img_got.resize(img_size)
        img[i]=k_pre.image.img_to_array(img_gotr)
    return img

In [10]:
#timeit.timeit(stmt=load_img(no_of_images,img_h,img_w))

In [11]:
load_img(no_of_images,img_h,img_w)

array([[[[ 41.,  40.,  38.],
         [ 62.,  61.,  59.],
         [ 61.,  60.,  58.],
         ...,
         [ 93.,  90.,  81.],
         [ 86.,  84.,  72.],
         [ 59.,  55.,  43.]],

        [[ 43.,  42.,  40.],
         [ 59.,  58.,  56.],
         [ 60.,  59.,  57.],
         ...,
         [116., 113., 104.],
         [108., 106.,  94.],
         [ 94.,  90.,  78.]],

        [[ 45.,  44.,  42.],
         [ 57.,  56.,  54.],
         [ 59.,  58.,  56.],
         ...,
         [124., 124., 116.],
         [118., 115., 106.],
         [107., 105.,  93.]],

        ...,

        [[ 53.,  48.,  16.],
         [ 53.,  48.,  16.],
         [ 53.,  48.,  16.],
         ...,
         [ 57.,  58.,  44.],
         [ 57.,  58.,  44.],
         [ 56.,  57.,  43.]],

        [[ 53.,  48.,  16.],
         [ 53.,  48.,  16.],
         [ 53.,  48.,  16.],
         ...,
         [ 57.,  58.,  44.],
         [ 57.,  58.,  44.],
         [ 57.,  58.,  44.]],

        [[ 53.,  48.,  16.],
       

In [12]:
img[0]

array([[[ 41.,  40.,  38.],
        [ 62.,  61.,  59.],
        [ 61.,  60.,  58.],
        ...,
        [ 93.,  90.,  81.],
        [ 86.,  84.,  72.],
        [ 59.,  55.,  43.]],

       [[ 43.,  42.,  40.],
        [ 59.,  58.,  56.],
        [ 60.,  59.,  57.],
        ...,
        [116., 113., 104.],
        [108., 106.,  94.],
        [ 94.,  90.,  78.]],

       [[ 45.,  44.,  42.],
        [ 57.,  56.,  54.],
        [ 59.,  58.,  56.],
        ...,
        [124., 124., 116.],
        [118., 115., 106.],
        [107., 105.,  93.]],

       ...,

       [[ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        ...,
        [ 57.,  58.,  44.],
        [ 57.,  58.,  44.],
        [ 56.,  57.,  43.]],

       [[ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        ...,
        [ 57.,  58.,  44.],
        [ 57.,  58.,  44.],
        [ 57.,  58.,  44.]],

       [[ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        [ 53.,  

In [13]:
x_train,x_test,y_train,y_test=t_split(img,lab_data,shuffle=True,test_size=0.2)

In [14]:
x_train.shape

(8000, 150, 150, 3)

In [15]:
x_train_norm=x_train/255
x_test_norm=x_test/255

In [16]:
x_train_norm=tf.convert_to_tensor(x_train_norm)
x_test_norm=tf.convert_to_tensor(x_test_norm)

In [26]:
def model():
    built=tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(32,(3,3),activation='relu',input_shape=(150,150,3)),
        tf.keras.layers.MaxPool2D(),
        tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
        tf.keras.layers.MaxPool2D(),
        tf.keras.layers.Conv2D(64,(3,3),activation='relu')
    ])
    built.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy','sparse_categorical_crossentropy'])
    return built

In [18]:
model_built=model()

In [19]:
model_built.add(tf.keras.layers.Flatten())
model_built.add(tf.keras.layers.Dense(64,activation='relu'))
model_built.add(tf.keras.layers.Dense(10,activation='softmax'))

In [21]:
Callbacks=tf.keras.callbacks.ModelCheckpoint(r'C:/Users/Victor/Desktop/Project_404/')

In [25]:
model_built.fit(x_train_norm,y_train,epochs=5,validation_split=0.2,verbose=1,batch_size=32)

ValueError: Error when checking input: expected conv2d_input to have shape (28, 28, 1) but got array with shape (150, 150, 3)