In [2]:
import tensorflow as tf

In [27]:
import keras.preprocessing as k_pre
import keras

In [4]:
import numpy as np
import random
from sklearn.model_selection import train_test_split as t_split
from PIL import Image
import pandas as pd
import timeit

In [5]:
data_dir=r'./10K_Model_Test/10k/'
lab_path=r'./10K_Model_Test/'

In [6]:
labels=pd.read_csv(lab_path+'labels.csv')
labels.head()

Labels
0  1.487000
1  3.471497
2  1.057709
3  3.586395
4  4.017059

In [7]:
lab_data=labels.iloc[:,].values
type(lab_data)

numpy.ndarray

In [8]:
lab_data[0]

array([1.487])

In [9]:
no_of_images=10000
img_h=150
img_w=150
img=np.zeros((no_of_images,img_h,img_w,3))
def load_img(no_of_images,img_h,img_w):
    
    img_size=(img_h,img_w)
    for i in range(no_of_images):
        img_got=Image.open(data_dir+'Grab'+str(i)+'.jpg')
        img_gotr=img_got.resize(img_size)
        img[i]=k_pre.image.img_to_array(img_gotr)
    return img

In [10]:
#timeit.timeit(stmt=load_img(no_of_images,img_h,img_w))

In [11]:
load_img(no_of_images,img_h,img_w)

array([[[[ 41.,  40.,  38.],
         [ 62.,  61.,  59.],
         [ 61.,  60.,  58.],
         ...,
         [ 93.,  90.,  81.],
         [ 86.,  84.,  72.],
         [ 59.,  55.,  43.]],

        [[ 43.,  42.,  40.],
         [ 59.,  58.,  56.],
         [ 60.,  59.,  57.],
         ...,
         [116., 113., 104.],
         [108., 106.,  94.],
         [ 94.,  90.,  78.]],

        [[ 45.,  44.,  42.],
         [ 57.,  56.,  54.],
         [ 59.,  58.,  56.],
         ...,
         [124., 124., 116.],
         [118., 115., 106.],
         [107., 105.,  93.]],

        ...,

        [[ 53.,  48.,  16.],
         [ 53.,  48.,  16.],
         [ 53.,  48.,  16.],
         ...,
         [ 57.,  58.,  44.],
         [ 57.,  58.,  44.],
         [ 56.,  57.,  43.]],

        [[ 53.,  48.,  16.],
         [ 53.,  48.,  16.],
         [ 53.,  48.,  16.],
         ...,
         [ 57.,  58.,  44.],
         [ 57.,  58.,  44.],
         [ 57.,  58.,  44.]],

        [[ 53.,  48.,  16.],
       

In [12]:
img[0]

array([[[ 41.,  40.,  38.],
        [ 62.,  61.,  59.],
        [ 61.,  60.,  58.],
        ...,
        [ 93.,  90.,  81.],
        [ 86.,  84.,  72.],
        [ 59.,  55.,  43.]],

       [[ 43.,  42.,  40.],
        [ 59.,  58.,  56.],
        [ 60.,  59.,  57.],
        ...,
        [116., 113., 104.],
        [108., 106.,  94.],
        [ 94.,  90.,  78.]],

       [[ 45.,  44.,  42.],
        [ 57.,  56.,  54.],
        [ 59.,  58.,  56.],
        ...,
        [124., 124., 116.],
        [118., 115., 106.],
        [107., 105.,  93.]],

       ...,

       [[ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        ...,
        [ 57.,  58.,  44.],
        [ 57.,  58.,  44.],
        [ 56.,  57.,  43.]],

       [[ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        ...,
        [ 57.,  58.,  44.],
        [ 57.,  58.,  44.],
        [ 57.,  58.,  44.]],

       [[ 53.,  48.,  16.],
        [ 53.,  48.,  16.],
        [ 53.,  

In [13]:
x_train,x_test,y_train,y_test=t_split(img,lab_data,shuffle=True,test_size=0.2)

In [14]:
x_train.shape

(8000, 150, 150, 3)

In [15]:
x_train_norm=x_train/255
x_test_norm=x_test/255

In [17]:
x_train_norm=x_train_norm.astype('float32')
x_train_norm=tf.convert_to_tensor(x_train_norm)
x_test_norm=x_test_norm.astype('float32')
x_test_norm=tf.convert_to_tensor(x_test_norm)
y_train=y_train.astype('float32')
y_test=y_test.astype('float32')

In [21]:
def model():
    built=tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(32,(3,3),activation='relu',input_shape=(150,150,3)),
        tf.keras.layers.MaxPool2D(),
        tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
        tf.keras.layers.MaxPool2D(),
        tf.keras.layers.Conv2D(64,(3,3),activation='relu')
    ])
    built.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy','mean_squared_error'])
    return built

In [22]:
model_built=model()

In [25]:
model_built.add(tf.keras.layers.Flatten())
model_built.add(tf.keras.layers.Dense(64,activation='relu'))
model_built.add(tf.keras.layers.Dense(1,activation='relu'))

In [28]:
Early_stop=keras.callbacks.EarlyStopping(
    monitor='val_loss',
    min_delta=1e-2,
    patience=3,verbose=1),
Checkpt=keras.callbacks.ModelCheckpoint(
    filepath=r'c:/Users/Victor/Desktop/Project_404/Model/mymodel_{epoch}.h5',
    save_best_only=True,
    monitor='val_loss',
    verbose=1)
reduce_lr = keras.callbacks.ReduceLROnPlateau(monitor='val_loss',
                                              factor=0.2,
                                              patience=5, min_lr=0.001)
Callbacks=[Early_stop,Checkpt,reduce_lr]

In [32]:
csv_logger = keras.callbacks.CSVLogger('C:/Users/Victor/Desktop/Project-404/Model/training.log')
Callbacks.append([csv_logger])
#tensorbrd=keras.callbacks.tensorboard_v1.TensorBoard(log_dir='C:/Users/Victor/Desktop/Project-404/Model/', histogram_freq=0, batch_size=32, write_graph=True)
#Callbacks.append(tensorbrd)

In [34]:
model_built.fit(x_train_norm,y_train,epochs=5,validation_split=0.2,verbose=1,batch_size=20,callbacks=Callbacks)

ResourceExhaustedError: OOM when allocating tensor with shape[6400,150,150,3] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:StridedSlice] name: strided_slice/

In [ ]:
predictions=model_built.predict(y_train)

In [ ]:
loss,acc=model_built.evaluate(predictions,y_test,batch_size=32,metric=['mean_squared_error','accuracy'])